---

name:
    websockets-prototype
version:
    0.1.0.0
github:
    costarastrology/websockets-prototype
homepage:
    https://github.com/costarastrology/websockets-prototype#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2022-present, Co-Star Astrology Society
category:
    Web
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Short, one-line summary of project here.

description: |
    Longer description of package here.

    Maybe include a simple usage example.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2

default-extensions:
    - DeriveGeneric
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - TupleSections
    - TypeApplications
    - TypeOperators
    - ViewPatterns


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    dependencies:
        - aeson
        - bytestring
        - containers
        - hedis
        - http-types
        - lifted-async
        - stm
        - time
        - wai
        - wai-websockets
        - websockets

executables:
    websockets-prototype:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - websockets-prototype
            - wai-extra
            - warp

tests:
    websockets-prototype-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - websockets-prototype
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
